POST http://127.0.0.1:8000/basic/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=nikole&password=123456
###

GET http://127.0.0.1:8000/basic/users/me HTTP/1.1
Content-Type: application/json
Authorization: bearer nikole
###

GET http://127.0.0.1:8000/basic/users HTTP/1.1
###