GET http://127.0.0.1:8000/usersdb_local HTTP/1.1
###

POST http://127.0.0.1:8000/usersdb_local HTTP/1.1
Content-Type: application/json

{
    "username": "deleteMe",
    "first_name": "Delete",
    "last_name": "Me",
    "age": 37,
    "email": "delete.me@gmail.com"
}
###

GET http://127.0.0.1:8000/usersdb_local/6893c8113d08c41f971e9b8b HTTP/1.1
###

GET http://127.0.0.1:8000/usersdb_local/query/?id=689514ef3d18c34b93b24e9e HTTP/1.1
###

DELETE http://127.0.0.1:8000/usersdb_local/689514ef3d18c34b93b24e9e HTTP/1.1
###

PUT http://127.0.0.1:8000/usersdb_local/689513997cec4f2205b4a5f0 HTTP/1.1
Content-Type: application/json

{
    "username": "andrea",
    "first_name": "Andrea",
    "last_name": "Mall",
    "age": 29,
    "email": "mall.a@gmail.com"
}