GET http://127.0.0.1:8000/users HTTP/1.1
###

GET http://127.0.0.1:8000/users/1 HTTP/1.1
###

GET http://127.0.0.1:8000/users/4 HTTP/1.1
###

GET http://127.0.0.1:8000/user_query/?id=1 HTTP/1.1
###

GET http://127.0.0.1:8000/user_query/?id=3 HTTP/1.1
###

GET http://127.0.0.1:8000/user_query/?id=luis HTTP/1.1
###